sudo: required

group: edge

services:
  - docker

install:
  - travis_retry docker build --tag bodsch/omgwtfssl .
  - docker run --detach --name omgwtfssl bodsch/omgwtfssl

script:
  - docker ps | grep -q omgwtfssl

after_success:
  - |
    [ "${TRAVIS_BRANCH}" == "master" ] && curl \
      --request POST \
      --header "Content-Type: application/json"  \
      --data '{"source_type":"Branch","source_name":"master"}' \
      https://registry.hub.docker.com/u/bodsch/omgwtfssl/trigger/${DOCKER_HUB_TOKEN}/
